/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MVC;





/**
 *
 * @authorYukun Sun (Group L WorkPackage 5)
 */
public class SatellitePanel extends javax.swing.JPanel {

    public SatellitePanel(){ initComponents();}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        latitude = new javax.swing.JTextField();
        longitude = new javax.swing.JTextField();
        time = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        latitude.setEditable(false);
        latitude.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        add(latitude, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 100));

        longitude.setEditable(false);
        longitude.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        add(longitude, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 220, 100));

        time.setEditable(false);
        time.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 220, 40));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    static javax.swing.JTextField latitude;
    static javax.swing.JTextField longitude;
    static javax.swing.JTextField time;
    // End of variables declaration//GEN-END:variables


    


   
}
