package MVC;

/**
 *
 * @author harry
 */
public class SpeechPanel extends javax.swing.JPanel {

    /**
     * Creates new form speechPanel
     */
    public SpeechPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        speP = new javax.swing.JPanel();
        smenu1 = new javax.swing.JPanel();
        sc1 = new javax.swing.JLabel();
        smenu2 = new javax.swing.JPanel();
        sc2 = new javax.swing.JLabel();
        smenu3 = new javax.swing.JPanel();
        sc3 = new javax.swing.JLabel();
        smenu4 = new javax.swing.JPanel();
        sc4 = new javax.swing.JLabel();
        smenu5 = new javax.swing.JPanel();
        sc5 = new javax.swing.JLabel();
        smenu6 = new javax.swing.JPanel();
        sc6 = new javax.swing.JLabel();

        speP.setPreferredSize(new java.awt.Dimension(203, 245));
        speP.setLayout(new java.awt.CardLayout());

        sc1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/speech1.png"))); // NOI18N

        javax.swing.GroupLayout smenu1Layout = new javax.swing.GroupLayout(smenu1);
        smenu1.setLayout(smenu1Layout);
        smenu1Layout.setHorizontalGroup(
            smenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sc1)
        );
        smenu1Layout.setVerticalGroup(
            smenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(smenu1Layout.createSequentialGroup()
                .addComponent(sc1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        speP.add(smenu1, "card2");

        sc2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/speech2.png"))); // NOI18N

        javax.swing.GroupLayout smenu2Layout = new javax.swing.GroupLayout(smenu2);
        smenu2.setLayout(smenu2Layout);
        smenu2Layout.setHorizontalGroup(
            smenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(smenu2Layout.createSequentialGroup()
                .addComponent(sc2)
                .addGap(0, 848, Short.MAX_VALUE))
        );
        smenu2Layout.setVerticalGroup(
            smenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(smenu2Layout.createSequentialGroup()
                .addComponent(sc2)
                .addGap(0, 320, Short.MAX_VALUE))
        );

        speP.add(smenu2, "card3");

        sc3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/speech3.png"))); // NOI18N

        javax.swing.GroupLayout smenu3Layout = new javax.swing.GroupLayout(smenu3);
        smenu3.setLayout(smenu3Layout);
        smenu3Layout.setHorizontalGroup(
            smenu3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(smenu3Layout.createSequentialGroup()
                .addComponent(sc3)
                .addGap(0, 848, Short.MAX_VALUE))
        );
        smenu3Layout.setVerticalGroup(
            smenu3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(smenu3Layout.createSequentialGroup()
                .addComponent(sc3)
                .addGap(0, 320, Short.MAX_VALUE))
        );

        speP.add(smenu3, "card4");

        sc4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/speech4.png"))); // NOI18N

        javax.swing.GroupLayout smenu4Layout = new javax.swing.GroupLayout(smenu4);
        smenu4.setLayout(smenu4Layout);
        smenu4Layout.setHorizontalGroup(
            smenu4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(smenu4Layout.createSequentialGroup()
                .addComponent(sc4)
                .addGap(0, 848, Short.MAX_VALUE))
        );
        smenu4Layout.setVerticalGroup(
            smenu4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(smenu4Layout.createSequentialGroup()
                .addComponent(sc4)
                .addGap(0, 320, Short.MAX_VALUE))
        );

        speP.add(smenu4, "card5");

        sc5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/speech5.png"))); // NOI18N

        javax.swing.GroupLayout smenu5Layout = new javax.swing.GroupLayout(smenu5);
        smenu5.setLayout(smenu5Layout);
        smenu5Layout.setHorizontalGroup(
            smenu5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(smenu5Layout.createSequentialGroup()
                .addComponent(sc5)
                .addGap(0, 848, Short.MAX_VALUE))
        );
        smenu5Layout.setVerticalGroup(
            smenu5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(smenu5Layout.createSequentialGroup()
                .addComponent(sc5)
                .addGap(0, 320, Short.MAX_VALUE))
        );

        speP.add(smenu5, "card6");

        sc6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/speech6.png"))); // NOI18N

        javax.swing.GroupLayout smenu6Layout = new javax.swing.GroupLayout(smenu6);
        smenu6.setLayout(smenu6Layout);
        smenu6Layout.setHorizontalGroup(
            smenu6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(smenu6Layout.createSequentialGroup()
                .addComponent(sc6)
                .addGap(0, 848, Short.MAX_VALUE))
        );
        smenu6Layout.setVerticalGroup(
            smenu6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(smenu6Layout.createSequentialGroup()
                .addComponent(sc6)
                .addGap(0, 320, Short.MAX_VALUE))
        );

        speP.add(smenu6, "card7");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(speP, javax.swing.GroupLayout.PREFERRED_SIZE, 1051, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(speP, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel sc1;
    private javax.swing.JLabel sc2;
    private javax.swing.JLabel sc3;
    private javax.swing.JLabel sc4;
    private javax.swing.JLabel sc5;
    private javax.swing.JLabel sc6;
    public static javax.swing.JPanel smenu1;
    public static javax.swing.JPanel smenu2;
    public static javax.swing.JPanel smenu3;
    public static javax.swing.JPanel smenu4;
    public static javax.swing.JPanel smenu5;
    public static javax.swing.JPanel smenu6;
    public static javax.swing.JPanel speP;
    // End of variables declaration//GEN-END:variables
}
