/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MVC;

/**
 *
 * @author 20521
 */
public class WhereToView extends javax.swing.JPanel {

    /**
     * Creates new form whereToPanel
     */
    public WhereToView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTextDisplay = new javax.swing.JPanel();
        jLabelTextDisplay = new javax.swing.JLabel();
        jTextFieldDestination = new javax.swing.JTextField();
        jPanelKeyBoard = new javax.swing.JPanel();
        jPanelKeyA = new javax.swing.JPanel();
        jLabelKeyA = new javax.swing.JLabel();
        jPanelKeyB = new javax.swing.JPanel();
        jLabelKeyB = new javax.swing.JLabel();
        jPanelKeyC = new javax.swing.JPanel();
        jLabelKeyC = new javax.swing.JLabel();
        jPanelKeyD = new javax.swing.JPanel();
        jLabelKeyD = new javax.swing.JLabel();
        jPanelKeyE = new javax.swing.JPanel();
        jLabelKeyE = new javax.swing.JLabel();
        jPanelKeyF = new javax.swing.JPanel();
        jLabelKeyF = new javax.swing.JLabel();
        jPanelKeyG = new javax.swing.JPanel();
        jLabelKeyG = new javax.swing.JLabel();
        jPanelKeyH = new javax.swing.JPanel();
        jLabelKeyH = new javax.swing.JLabel();
        jPanelKeyI = new javax.swing.JPanel();
        jLabelKeyI = new javax.swing.JLabel();
        jPanelKeyJ = new javax.swing.JPanel();
        jLabelKeyJ = new javax.swing.JLabel();
        jPanelKeyK = new javax.swing.JPanel();
        jLabelKeyK = new javax.swing.JLabel();
        jPanelKeyL = new javax.swing.JPanel();
        jLabelKeyL = new javax.swing.JLabel();
        jPanelKeyM = new javax.swing.JPanel();
        jLabelKeyM = new javax.swing.JLabel();
        jPanelKeyN = new javax.swing.JPanel();
        jLabelKeyN = new javax.swing.JLabel();
        jPanelKeyO = new javax.swing.JPanel();
        jLabelKeyO = new javax.swing.JLabel();
        jPanelKeyP = new javax.swing.JPanel();
        jLabelKeyP = new javax.swing.JLabel();
        jPanelKeyQ = new javax.swing.JPanel();
        jLabelKeyQ = new javax.swing.JLabel();
        jPanelKeyR = new javax.swing.JPanel();
        jLabelKeyR = new javax.swing.JLabel();
        jPanelKeyS = new javax.swing.JPanel();
        jLabelKeyS = new javax.swing.JLabel();
        jPanelKeyT = new javax.swing.JPanel();
        jLabelKeyT = new javax.swing.JLabel();
        jPanelKeyU = new javax.swing.JPanel();
        jLabelKeyU = new javax.swing.JLabel();
        jPanelKeyV = new javax.swing.JPanel();
        jLabelKeyV = new javax.swing.JLabel();
        jPanelKeyW = new javax.swing.JPanel();
        jLabelKeyW = new javax.swing.JLabel();
        jPanelKeyX = new javax.swing.JPanel();
        jLabelKeyX = new javax.swing.JLabel();
        jPanelKeyY = new javax.swing.JPanel();
        jLabelKeyY = new javax.swing.JLabel();
        jPanelKeyZ = new javax.swing.JPanel();
        jLabelKeyZ = new javax.swing.JLabel();
        jPanelKeySpace = new javax.swing.JPanel();
        jLabelKeySpace = new javax.swing.JLabel();
        jPanelKeyNext = new javax.swing.JPanel();
        jLabelKeyNext = new javax.swing.JLabel();
        jPanelKeyOne = new javax.swing.JPanel();
        jLabelKeyOne = new javax.swing.JLabel();
        jPanelKeyTwo = new javax.swing.JPanel();
        jLabelKeyTwo = new javax.swing.JLabel();
        jPanelKeyThree = new javax.swing.JPanel();
        jLabelKeyThree = new javax.swing.JLabel();
        jPanelKeyFour = new javax.swing.JPanel();
        jLabelKeyFour = new javax.swing.JLabel();
        jPanelKeyFive = new javax.swing.JPanel();
        jLabelKeyFive = new javax.swing.JLabel();
        jPanelKeySix = new javax.swing.JPanel();
        jLabelKeySix = new javax.swing.JLabel();
        jPanelKeySeven = new javax.swing.JPanel();
        jLabelKeySeven = new javax.swing.JLabel();
        jPanelKeyEight = new javax.swing.JPanel();
        jLabelKeyEight = new javax.swing.JLabel();
        jPanelKeyNine = new javax.swing.JPanel();
        jLabelKeyNine = new javax.swing.JLabel();
        jPanelKeyZero = new javax.swing.JPanel();
        jLabelKeyZero = new javax.swing.JLabel();
        jPanelKeyDel = new javax.swing.JPanel();
        jLabelKeyDel = new javax.swing.JLabel();
        jPanelKeyPrev = new javax.swing.JPanel();
        jLabelKeyPrev = new javax.swing.JLabel();
        jPanelAlphaKeyBoard = new javax.swing.JPanel();
        jLabelAlphaKeyBoard = new javax.swing.JLabel();
        jPanelNumKeyBoard = new javax.swing.JPanel();
        jLabelNumKeyBoard = new javax.swing.JLabel();
        jPanelSubmit = new javax.swing.JPanel();
        jPanelSubmitButton = new javax.swing.JPanel();
        jLabelSubmitButton = new javax.swing.JLabel();
        jPanelSubmitHighlight = new javax.swing.JPanel();
        jLabelSubmitHighlight = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(203, 245));

        jPanelTextDisplay.setPreferredSize(new java.awt.Dimension(150, 33));

        jLabelTextDisplay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/text_adv.png"))); // NOI18N

        jTextFieldDestination.setPreferredSize(new java.awt.Dimension(130, 24));

        javax.swing.GroupLayout jPanelTextDisplayLayout = new javax.swing.GroupLayout(jPanelTextDisplay);
        jPanelTextDisplay.setLayout(jPanelTextDisplayLayout);
        jPanelTextDisplayLayout.setHorizontalGroup(
            jPanelTextDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
            .addGroup(jPanelTextDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelTextDisplayLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelTextDisplay)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jPanelTextDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelTextDisplayLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jTextFieldDestination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelTextDisplayLayout.setVerticalGroup(
            jPanelTextDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
            .addGroup(jPanelTextDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelTextDisplayLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelTextDisplay)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jPanelTextDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelTextDisplayLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jTextFieldDestination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanelKeyBoard.setPreferredSize(new java.awt.Dimension(203, 212));
        jPanelKeyBoard.setLayout(new java.awt.CardLayout());

        jPanelKeyA.setPreferredSize(new java.awt.Dimension(203, 212));

        jLabelKeyA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/key_a.png"))); // NOI18N

        javax.swing.GroupLayout jPanelKeyALayout = new javax.swing.GroupLayout(jPanelKeyA);
        jPanelKeyA.setLayout(jPanelKeyALayout);
        jPanelKeyALayout.setHorizontalGroup(
            jPanelKeyALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 203, Short.MAX_VALUE)
            .addGroup(jPanelKeyALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelKeyALayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelKeyA)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelKeyALayout.setVerticalGroup(
            jPanelKeyALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 212, Short.MAX_VALUE)
            .addGroup(jPanelKeyALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelKeyALayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelKeyA)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanelKeyBoard.add(jPanelKeyA, "card2");

        jPanelKeyB.setPreferredSize(new java.awt.Dimension(203, 212));

        jLabelKeyB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/key_b.png"))); // NOI18N

        javax.swing.GroupLayout jPanelKeyBLayout = new javax.swing.GroupLayout(jPanelKeyB);
        jPanelKeyB.setLayout(jPanelKeyBLayout);
        jPanelKeyBLayout.setHorizontalGroup(
            jPanelKeyBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 203, Short.MAX_VALUE)
            .addGroup(jPanelKeyBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelKeyBLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelKeyB)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelKeyBLayout.setVerticalGroup(
            jPanelKeyBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 212, Short.MAX_VALUE)
            .addGroup(jPanelKeyBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelKeyBLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelKeyB)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanelKeyBoard.add(jPanelKeyB, "card3");

        jLabelKeyC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/key_c.png"))); // NOI18N

        javax.swing.GroupLayout jPanelKeyCLayout = new javax.swing.GroupLayout(jPanelKeyC);
        jPanelKeyC.setLayout(jPanelKeyCLayout);
        jPanelKeyCLayout.setHorizontalGroup(
            jPanelKeyCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 203, Short.MAX_VALUE)
            .addGroup(jPanelKeyCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelKeyCLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelKeyC)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelKeyCLayout.setVerticalGroup(
            jPanelKeyCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 212, Short.MAX_VALUE)
            .addGroup(jPanelKeyCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelKeyCLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelKeyC)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanelKeyBoard.add(jPanelKeyC, "card4");

        jLabelKeyD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/key_d.png"))); // NOI18N

        javax.swing.GroupLayout jPanelKeyDLayout = new javax.swing.GroupLayout(jPanelKeyD);
        jPanelKeyD.setLayout(jPanelKeyDLayout);
        jPanelKeyDLayout.setHorizontalGroup(
            jPanelKeyDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 203, Short.MAX_VALUE)
            .addGroup(jPanelKeyDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelKeyDLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelKeyD)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelKeyDLayout.setVerticalGroup(
            jPanelKeyDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 212, Short.MAX_VALUE)
            .addGroup(jPanelKeyDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelKeyDLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelKeyD)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanelKeyBoard.add(jPanelKeyD, "card5");

        jLabelKeyE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/key_e.png"))); // NOI18N

        javax.swing.GroupLayout jPanelKeyELayout = new javax.swing.GroupLayout(jPanelKeyE);
        jPanelKeyE.setLayout(jPanelKeyELayout);
        jPanelKeyELayout.setHorizontalGroup(
            jPanelKeyELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 203, Short.MAX_VALUE)
            .addGroup(jPanelKeyELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelKeyELayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelKeyE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelKeyELayout.setVerticalGroup(
            jPanelKeyELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 212, Short.MAX_VALUE)
            .addGroup(jPanelKeyELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelKeyELayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelKeyE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanelKeyBoard.add(jPanelKeyE, "card6");

        jLabelKeyF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/key_f.png"))); // NOI18N

        javax.swing.GroupLayout jPanelKeyFLayout = new javax.swing.GroupLayout(jPanelKeyF);
        jPanelKeyF.setLayout(jPanelKeyFLayout);
        jPanelKeyFLayout.setHorizontalGroup(
            jPanelKeyFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 203, Short.MAX_VALUE)
            .addGroup(jPanelKeyFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelKeyFLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelKeyF)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelKeyFLayout.setVerticalGroup(
            jPanelKeyFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 212, Short.MAX_VALUE)
            .addGroup(jPanelKeyFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelKeyFLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelKeyF)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanelKeyBoard.add(jPanelKeyF, "card7");

        jLabelKeyG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/key_g.png"))); // NOI18N

        javax.swing.GroupLayout jPanelKeyGLayout = new javax.swing.GroupLayout(jPanelKeyG);
        jPanelKeyG.setLayout(jPanelKeyGLayout);
        jPanelKeyGLayout.setHorizontalGroup(
            jPanelKeyGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 203, Short.MAX_VALUE)
            .addGroup(jPanelKeyGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelKeyGLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelKeyG)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelKeyGLayout.setVerticalGroup(
            jPanelKeyGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 212, Short.MAX_VALUE)
            .addGroup(jPanelKeyGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelKeyGLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelKeyG)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanelKeyBoard.add(jPanelKeyG, "card8");

        jLabelKeyH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/key_h.png"))); // NOI18N

        javax.swing.GroupLayout jPanelKeyHLayout = new javax.swing.GroupLayout(jPanelKeyH);
        jPanelKeyH.setLayout(jPanelKeyHLayout);
        jPanelKeyHLayout.setHorizontalGroup(
            jPanelKeyHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 203, Short.MAX_VALUE)
            .addGroup(jPanelKeyHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelKeyHLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelKeyH)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelKeyHLayout.setVerticalGroup(
            jPanelKeyHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 212, Short.MAX_VALUE)
            .addGroup(jPanelKeyHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelKeyHLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelKeyH)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanelKeyBoard.add(jPanelKeyH, "card9");

        jLabelKeyI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/key_i.png"))); // NOI18N

        javax.swing.GroupLayout jPanelKeyILayout = new javax.swing.GroupLayout(jPanelKeyI);
        jPanelKeyI.setLayout(jPanelKeyILayout);
        jPanelKeyILayout.setHorizontalGroup(
            jPanelKeyILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 203, Short.MAX_VALUE)
            .addGroup(jPanelKeyILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelKeyILayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelKeyI)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelKeyILayout.setVerticalGroup(
            jPanelKeyILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 212, Short.MAX_VALUE)
            .addGroup(jPanelKeyILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelKeyILayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelKeyI)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanelKeyBoard.add(jPanelKeyI, "card10");

        jLabelKeyJ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/key_j.png"))); // NOI18N

        javax.swing.GroupLayout jPanelKeyJLayout = new javax.swing.GroupLayout(jPanelKeyJ);
        jPanelKeyJ.setLayout(jPanelKeyJLayout);
        jPanelKeyJLayout.setHorizontalGroup(
            jPanelKeyJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 203, Short.MAX_VALUE)
            .addGroup(jPanelKeyJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelKeyJLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelKeyJ)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelKeyJLayout.setVerticalGroup(
            jPanelKeyJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 212, Short.MAX_VALUE)
            .addGroup(jPanelKeyJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelKeyJLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelKeyJ)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanelKeyBoard.add(jPanelKeyJ, "card11");

        jLabelKeyK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/key_k.png"))); // NOI18N

        javax.swing.GroupLayout jPanelKeyKLayout = new javax.swing.GroupLayout(jPanelKeyK);
        jPanelKeyK.setLayout(jPanelKeyKLayout);
        jPanelKeyKLayout.setHorizontalGroup(
            jPanelKeyKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 203, Short.MAX_VALUE)
            .addGroup(jPanelKeyKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelKeyKLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelKeyK)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelKeyKLayout.setVerticalGroup(
            jPanelKeyKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 212, Short.MAX_VALUE)
            .addGroup(jPanelKeyKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelKeyKLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelKeyK)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanelKeyBoard.add(jPanelKeyK, "card12");

        jLabelKeyL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/key_l.png"))); // NOI18N

        javax.swing.GroupLayout jPanelKeyLLayout = new javax.swing.GroupLayout(jPanelKeyL);
        jPanelKeyL.setLayout(jPanelKeyLLayout);
        jPanelKeyLLayout.setHorizontalGroup(
            jPanelKeyLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 203, Short.MAX_VALUE)
            .addGroup(jPanelKeyLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelKeyLLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelKeyL)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelKeyLLayout.setVerticalGroup(
            jPanelKeyLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 212, Short.MAX_VALUE)
            .addGroup(jPanelKeyLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelKeyLLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelKeyL)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanelKeyBoard.add(jPanelKeyL, "card13");

        jLabelKeyM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/key_m.png"))); // NOI18N

        javax.swing.GroupLayout jPanelKeyMLayout = new javax.swing.GroupLayout(jPanelKeyM);
        jPanelKeyM.setLayout(jPanelKeyMLayout);
        jPanelKeyMLayout.setHorizontalGroup(
            jPanelKeyMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 203, Short.MAX_VALUE)
            .addGroup(jPanelKeyMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelKeyMLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelKeyM)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelKeyMLayout.setVerticalGroup(
            jPanelKeyMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 212, Short.MAX_VALUE)
            .addGroup(jPanelKeyMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelKeyMLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelKeyM)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanelKeyBoard.add(jPanelKeyM, "card14");

        jLabelKeyN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/key_n.png"))); // NOI18N

        javax.swing.GroupLayout jPanelKeyNLayout = new javax.swing.GroupLayout(jPanelKeyN);
        jPanelKeyN.setLayout(jPanelKeyNLayout);
        jPanelKeyNLayout.setHorizontalGroup(
            jPanelKeyNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 203, Short.MAX_VALUE)
            .addGroup(jPanelKeyNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelKeyNLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelKeyN)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelKeyNLayout.setVerticalGroup(
            jPanelKeyNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 212, Short.MAX_VALUE)
            .addGroup(jPanelKeyNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelKeyNLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelKeyN)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanelKeyBoard.add(jPanelKeyN, "card15");

        jLabelKeyO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/key_o.png"))); // NOI18N

        javax.swing.GroupLayout jPanelKeyOLayout = new javax.swing.GroupLayout(jPanelKeyO);
        jPanelKeyO.setLayout(jPanelKeyOLayout);
        jPanelKeyOLayout.setHorizontalGroup(
            jPanelKeyOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 203, Short.MAX_VALUE)
            .addGroup(jPanelKeyOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelKeyOLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelKeyO)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelKeyOLayout.setVerticalGroup(
            jPanelKeyOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 212, Short.MAX_VALUE)
            .addGroup(jPanelKeyOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelKeyOLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelKeyO)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanelKeyBoard.add(jPanelKeyO, "card16");

        jLabelKeyP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/key_p.png"))); // NOI18N

        javax.swing.GroupLayout jPanelKeyPLayout = new javax.swing.GroupLayout(jPanelKeyP);
        jPanelKeyP.setLayout(jPanelKeyPLayout);
        jPanelKeyPLayout.setHorizontalGroup(
            jPanelKeyPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 203, Short.MAX_VALUE)
            .addGroup(jPanelKeyPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelKeyPLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelKeyP)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelKeyPLayout.setVerticalGroup(
            jPanelKeyPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 212, Short.MAX_VALUE)
            .addGroup(jPanelKeyPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelKeyPLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelKeyP)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanelKeyBoard.add(jPanelKeyP, "card17");

        jLabelKeyQ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/key_q.png"))); // NOI18N

        javax.swing.GroupLayout jPanelKeyQLayout = new javax.swing.GroupLayout(jPanelKeyQ);
        jPanelKeyQ.setLayout(jPanelKeyQLayout);
        jPanelKeyQLayout.setHorizontalGroup(
            jPanelKeyQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 203, Short.MAX_VALUE)
            .addGroup(jPanelKeyQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelKeyQLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelKeyQ)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelKeyQLayout.setVerticalGroup(
            jPanelKeyQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 212, Short.MAX_VALUE)
            .addGroup(jPanelKeyQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelKeyQLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelKeyQ)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanelKeyBoard.add(jPanelKeyQ, "card18");

        jLabelKeyR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/key_r.png"))); // NOI18N

        javax.swing.GroupLayout jPanelKeyRLayout = new javax.swing.GroupLayout(jPanelKeyR);
        jPanelKeyR.setLayout(jPanelKeyRLayout);
        jPanelKeyRLayout.setHorizontalGroup(
            jPanelKeyRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 203, Short.MAX_VALUE)
            .addGroup(jPanelKeyRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelKeyRLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelKeyR)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelKeyRLayout.setVerticalGroup(
            jPanelKeyRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 212, Short.MAX_VALUE)
            .addGroup(jPanelKeyRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelKeyRLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelKeyR)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanelKeyBoard.add(jPanelKeyR, "card19");

        jLabelKeyS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/key_s.png"))); // NOI18N

        javax.swing.GroupLayout jPanelKeySLayout = new javax.swing.GroupLayout(jPanelKeyS);
        jPanelKeyS.setLayout(jPanelKeySLayout);
        jPanelKeySLayout.setHorizontalGroup(
            jPanelKeySLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 203, Short.MAX_VALUE)
            .addGroup(jPanelKeySLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelKeySLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelKeyS)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelKeySLayout.setVerticalGroup(
            jPanelKeySLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 212, Short.MAX_VALUE)
            .addGroup(jPanelKeySLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelKeySLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelKeyS)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanelKeyBoard.add(jPanelKeyS, "card20");

        jLabelKeyT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/key_t.png"))); // NOI18N

        javax.swing.GroupLayout jPanelKeyTLayout = new javax.swing.GroupLayout(jPanelKeyT);
        jPanelKeyT.setLayout(jPanelKeyTLayout);
        jPanelKeyTLayout.setHorizontalGroup(
            jPanelKeyTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 203, Short.MAX_VALUE)
            .addGroup(jPanelKeyTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelKeyTLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelKeyT)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelKeyTLayout.setVerticalGroup(
            jPanelKeyTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 212, Short.MAX_VALUE)
            .addGroup(jPanelKeyTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelKeyTLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelKeyT)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanelKeyBoard.add(jPanelKeyT, "card21");

        jLabelKeyU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/key_u.png"))); // NOI18N

        javax.swing.GroupLayout jPanelKeyULayout = new javax.swing.GroupLayout(jPanelKeyU);
        jPanelKeyU.setLayout(jPanelKeyULayout);
        jPanelKeyULayout.setHorizontalGroup(
            jPanelKeyULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 203, Short.MAX_VALUE)
            .addGroup(jPanelKeyULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelKeyULayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelKeyU)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelKeyULayout.setVerticalGroup(
            jPanelKeyULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 212, Short.MAX_VALUE)
            .addGroup(jPanelKeyULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelKeyULayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelKeyU)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanelKeyBoard.add(jPanelKeyU, "card22");

        jLabelKeyV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/key_v.png"))); // NOI18N

        javax.swing.GroupLayout jPanelKeyVLayout = new javax.swing.GroupLayout(jPanelKeyV);
        jPanelKeyV.setLayout(jPanelKeyVLayout);
        jPanelKeyVLayout.setHorizontalGroup(
            jPanelKeyVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 203, Short.MAX_VALUE)
            .addGroup(jPanelKeyVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelKeyVLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelKeyV)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelKeyVLayout.setVerticalGroup(
            jPanelKeyVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 212, Short.MAX_VALUE)
            .addGroup(jPanelKeyVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelKeyVLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelKeyV)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanelKeyBoard.add(jPanelKeyV, "card23");

        jLabelKeyW.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/key_w.png"))); // NOI18N

        javax.swing.GroupLayout jPanelKeyWLayout = new javax.swing.GroupLayout(jPanelKeyW);
        jPanelKeyW.setLayout(jPanelKeyWLayout);
        jPanelKeyWLayout.setHorizontalGroup(
            jPanelKeyWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 203, Short.MAX_VALUE)
            .addGroup(jPanelKeyWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelKeyWLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelKeyW)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelKeyWLayout.setVerticalGroup(
            jPanelKeyWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 212, Short.MAX_VALUE)
            .addGroup(jPanelKeyWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelKeyWLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelKeyW)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanelKeyBoard.add(jPanelKeyW, "card24");

        jLabelKeyX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/key_x.png"))); // NOI18N

        javax.swing.GroupLayout jPanelKeyXLayout = new javax.swing.GroupLayout(jPanelKeyX);
        jPanelKeyX.setLayout(jPanelKeyXLayout);
        jPanelKeyXLayout.setHorizontalGroup(
            jPanelKeyXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 203, Short.MAX_VALUE)
            .addGroup(jPanelKeyXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelKeyXLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelKeyX)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelKeyXLayout.setVerticalGroup(
            jPanelKeyXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 212, Short.MAX_VALUE)
            .addGroup(jPanelKeyXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelKeyXLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelKeyX)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanelKeyBoard.add(jPanelKeyX, "card25");

        jLabelKeyY.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/key_y.png"))); // NOI18N

        javax.swing.GroupLayout jPanelKeyYLayout = new javax.swing.GroupLayout(jPanelKeyY);
        jPanelKeyY.setLayout(jPanelKeyYLayout);
        jPanelKeyYLayout.setHorizontalGroup(
            jPanelKeyYLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 203, Short.MAX_VALUE)
            .addGroup(jPanelKeyYLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelKeyYLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelKeyY)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelKeyYLayout.setVerticalGroup(
            jPanelKeyYLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 212, Short.MAX_VALUE)
            .addGroup(jPanelKeyYLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelKeyYLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelKeyY)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanelKeyBoard.add(jPanelKeyY, "card26");

        jLabelKeyZ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/key_z.png"))); // NOI18N

        javax.swing.GroupLayout jPanelKeyZLayout = new javax.swing.GroupLayout(jPanelKeyZ);
        jPanelKeyZ.setLayout(jPanelKeyZLayout);
        jPanelKeyZLayout.setHorizontalGroup(
            jPanelKeyZLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 203, Short.MAX_VALUE)
            .addGroup(jPanelKeyZLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelKeyZLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelKeyZ)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelKeyZLayout.setVerticalGroup(
            jPanelKeyZLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 212, Short.MAX_VALUE)
            .addGroup(jPanelKeyZLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelKeyZLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelKeyZ)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanelKeyBoard.add(jPanelKeyZ, "card27");

        jLabelKeySpace.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/key_space.png"))); // NOI18N

        javax.swing.GroupLayout jPanelKeySpaceLayout = new javax.swing.GroupLayout(jPanelKeySpace);
        jPanelKeySpace.setLayout(jPanelKeySpaceLayout);
        jPanelKeySpaceLayout.setHorizontalGroup(
            jPanelKeySpaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 203, Short.MAX_VALUE)
            .addGroup(jPanelKeySpaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelKeySpaceLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelKeySpace)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelKeySpaceLayout.setVerticalGroup(
            jPanelKeySpaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 212, Short.MAX_VALUE)
            .addGroup(jPanelKeySpaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelKeySpaceLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelKeySpace)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanelKeyBoard.add(jPanelKeySpace, "card28");

        jLabelKeyNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/key_next.png"))); // NOI18N

        javax.swing.GroupLayout jPanelKeyNextLayout = new javax.swing.GroupLayout(jPanelKeyNext);
        jPanelKeyNext.setLayout(jPanelKeyNextLayout);
        jPanelKeyNextLayout.setHorizontalGroup(
            jPanelKeyNextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 203, Short.MAX_VALUE)
            .addGroup(jPanelKeyNextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelKeyNextLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelKeyNext)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelKeyNextLayout.setVerticalGroup(
            jPanelKeyNextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 212, Short.MAX_VALUE)
            .addGroup(jPanelKeyNextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelKeyNextLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelKeyNext)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanelKeyBoard.add(jPanelKeyNext, "card29");

        jLabelKeyOne.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/key_1.png"))); // NOI18N

        javax.swing.GroupLayout jPanelKeyOneLayout = new javax.swing.GroupLayout(jPanelKeyOne);
        jPanelKeyOne.setLayout(jPanelKeyOneLayout);
        jPanelKeyOneLayout.setHorizontalGroup(
            jPanelKeyOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 203, Short.MAX_VALUE)
            .addGroup(jPanelKeyOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelKeyOneLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelKeyOne)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelKeyOneLayout.setVerticalGroup(
            jPanelKeyOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 212, Short.MAX_VALUE)
            .addGroup(jPanelKeyOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelKeyOneLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelKeyOne)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanelKeyBoard.add(jPanelKeyOne, "card30");

        jLabelKeyTwo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/key_2.png"))); // NOI18N

        javax.swing.GroupLayout jPanelKeyTwoLayout = new javax.swing.GroupLayout(jPanelKeyTwo);
        jPanelKeyTwo.setLayout(jPanelKeyTwoLayout);
        jPanelKeyTwoLayout.setHorizontalGroup(
            jPanelKeyTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 203, Short.MAX_VALUE)
            .addGroup(jPanelKeyTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelKeyTwoLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelKeyTwo)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelKeyTwoLayout.setVerticalGroup(
            jPanelKeyTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 212, Short.MAX_VALUE)
            .addGroup(jPanelKeyTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelKeyTwoLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelKeyTwo)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanelKeyBoard.add(jPanelKeyTwo, "card31");

        jLabelKeyThree.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/key_3.png"))); // NOI18N

        javax.swing.GroupLayout jPanelKeyThreeLayout = new javax.swing.GroupLayout(jPanelKeyThree);
        jPanelKeyThree.setLayout(jPanelKeyThreeLayout);
        jPanelKeyThreeLayout.setHorizontalGroup(
            jPanelKeyThreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 203, Short.MAX_VALUE)
            .addGroup(jPanelKeyThreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelKeyThreeLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelKeyThree)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelKeyThreeLayout.setVerticalGroup(
            jPanelKeyThreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 212, Short.MAX_VALUE)
            .addGroup(jPanelKeyThreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelKeyThreeLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelKeyThree)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanelKeyBoard.add(jPanelKeyThree, "card32");

        jLabelKeyFour.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/key_4.png"))); // NOI18N

        javax.swing.GroupLayout jPanelKeyFourLayout = new javax.swing.GroupLayout(jPanelKeyFour);
        jPanelKeyFour.setLayout(jPanelKeyFourLayout);
        jPanelKeyFourLayout.setHorizontalGroup(
            jPanelKeyFourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 203, Short.MAX_VALUE)
            .addGroup(jPanelKeyFourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelKeyFourLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelKeyFour)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelKeyFourLayout.setVerticalGroup(
            jPanelKeyFourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 212, Short.MAX_VALUE)
            .addGroup(jPanelKeyFourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelKeyFourLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelKeyFour)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanelKeyBoard.add(jPanelKeyFour, "card33");

        jLabelKeyFive.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/key_5.png"))); // NOI18N

        javax.swing.GroupLayout jPanelKeyFiveLayout = new javax.swing.GroupLayout(jPanelKeyFive);
        jPanelKeyFive.setLayout(jPanelKeyFiveLayout);
        jPanelKeyFiveLayout.setHorizontalGroup(
            jPanelKeyFiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 203, Short.MAX_VALUE)
            .addGroup(jPanelKeyFiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelKeyFiveLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelKeyFive)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelKeyFiveLayout.setVerticalGroup(
            jPanelKeyFiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 212, Short.MAX_VALUE)
            .addGroup(jPanelKeyFiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelKeyFiveLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelKeyFive)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanelKeyBoard.add(jPanelKeyFive, "card34");

        jLabelKeySix.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/key_6.png"))); // NOI18N

        javax.swing.GroupLayout jPanelKeySixLayout = new javax.swing.GroupLayout(jPanelKeySix);
        jPanelKeySix.setLayout(jPanelKeySixLayout);
        jPanelKeySixLayout.setHorizontalGroup(
            jPanelKeySixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 203, Short.MAX_VALUE)
            .addGroup(jPanelKeySixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelKeySixLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelKeySix)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelKeySixLayout.setVerticalGroup(
            jPanelKeySixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 212, Short.MAX_VALUE)
            .addGroup(jPanelKeySixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelKeySixLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelKeySix)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanelKeyBoard.add(jPanelKeySix, "card35");

        jLabelKeySeven.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/key_7.png"))); // NOI18N

        javax.swing.GroupLayout jPanelKeySevenLayout = new javax.swing.GroupLayout(jPanelKeySeven);
        jPanelKeySeven.setLayout(jPanelKeySevenLayout);
        jPanelKeySevenLayout.setHorizontalGroup(
            jPanelKeySevenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 203, Short.MAX_VALUE)
            .addGroup(jPanelKeySevenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelKeySevenLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelKeySeven)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelKeySevenLayout.setVerticalGroup(
            jPanelKeySevenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 212, Short.MAX_VALUE)
            .addGroup(jPanelKeySevenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelKeySevenLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelKeySeven)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanelKeyBoard.add(jPanelKeySeven, "card36");

        jLabelKeyEight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/key_8.png"))); // NOI18N

        javax.swing.GroupLayout jPanelKeyEightLayout = new javax.swing.GroupLayout(jPanelKeyEight);
        jPanelKeyEight.setLayout(jPanelKeyEightLayout);
        jPanelKeyEightLayout.setHorizontalGroup(
            jPanelKeyEightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 203, Short.MAX_VALUE)
            .addGroup(jPanelKeyEightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelKeyEightLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelKeyEight)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelKeyEightLayout.setVerticalGroup(
            jPanelKeyEightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 212, Short.MAX_VALUE)
            .addGroup(jPanelKeyEightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelKeyEightLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelKeyEight)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanelKeyBoard.add(jPanelKeyEight, "card37");

        jLabelKeyNine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/key_9.png"))); // NOI18N

        javax.swing.GroupLayout jPanelKeyNineLayout = new javax.swing.GroupLayout(jPanelKeyNine);
        jPanelKeyNine.setLayout(jPanelKeyNineLayout);
        jPanelKeyNineLayout.setHorizontalGroup(
            jPanelKeyNineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 203, Short.MAX_VALUE)
            .addGroup(jPanelKeyNineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelKeyNineLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelKeyNine)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelKeyNineLayout.setVerticalGroup(
            jPanelKeyNineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 212, Short.MAX_VALUE)
            .addGroup(jPanelKeyNineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelKeyNineLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelKeyNine)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanelKeyBoard.add(jPanelKeyNine, "card38");

        jLabelKeyZero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/key_0.png"))); // NOI18N

        javax.swing.GroupLayout jPanelKeyZeroLayout = new javax.swing.GroupLayout(jPanelKeyZero);
        jPanelKeyZero.setLayout(jPanelKeyZeroLayout);
        jPanelKeyZeroLayout.setHorizontalGroup(
            jPanelKeyZeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 203, Short.MAX_VALUE)
            .addGroup(jPanelKeyZeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelKeyZeroLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelKeyZero)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelKeyZeroLayout.setVerticalGroup(
            jPanelKeyZeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 212, Short.MAX_VALUE)
            .addGroup(jPanelKeyZeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelKeyZeroLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelKeyZero)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanelKeyBoard.add(jPanelKeyZero, "card39");

        jLabelKeyDel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/key_del.png"))); // NOI18N

        javax.swing.GroupLayout jPanelKeyDelLayout = new javax.swing.GroupLayout(jPanelKeyDel);
        jPanelKeyDel.setLayout(jPanelKeyDelLayout);
        jPanelKeyDelLayout.setHorizontalGroup(
            jPanelKeyDelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 203, Short.MAX_VALUE)
            .addGroup(jPanelKeyDelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelKeyDelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelKeyDel)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelKeyDelLayout.setVerticalGroup(
            jPanelKeyDelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 212, Short.MAX_VALUE)
            .addGroup(jPanelKeyDelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelKeyDelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelKeyDel)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanelKeyBoard.add(jPanelKeyDel, "card40");

        jLabelKeyPrev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/key_prev.png"))); // NOI18N

        javax.swing.GroupLayout jPanelKeyPrevLayout = new javax.swing.GroupLayout(jPanelKeyPrev);
        jPanelKeyPrev.setLayout(jPanelKeyPrevLayout);
        jPanelKeyPrevLayout.setHorizontalGroup(
            jPanelKeyPrevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 203, Short.MAX_VALUE)
            .addGroup(jPanelKeyPrevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelKeyPrevLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelKeyPrev)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelKeyPrevLayout.setVerticalGroup(
            jPanelKeyPrevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 212, Short.MAX_VALUE)
            .addGroup(jPanelKeyPrevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelKeyPrevLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelKeyPrev)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanelKeyBoard.add(jPanelKeyPrev, "card41");

        jLabelAlphaKeyBoard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/alphaKeyBoard.png"))); // NOI18N

        javax.swing.GroupLayout jPanelAlphaKeyBoardLayout = new javax.swing.GroupLayout(jPanelAlphaKeyBoard);
        jPanelAlphaKeyBoard.setLayout(jPanelAlphaKeyBoardLayout);
        jPanelAlphaKeyBoardLayout.setHorizontalGroup(
            jPanelAlphaKeyBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 203, Short.MAX_VALUE)
            .addGroup(jPanelAlphaKeyBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelAlphaKeyBoardLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelAlphaKeyBoard)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelAlphaKeyBoardLayout.setVerticalGroup(
            jPanelAlphaKeyBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 212, Short.MAX_VALUE)
            .addGroup(jPanelAlphaKeyBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelAlphaKeyBoardLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelAlphaKeyBoard)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanelKeyBoard.add(jPanelAlphaKeyBoard, "card42");

        jLabelNumKeyBoard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/numKeyBoard.png"))); // NOI18N

        javax.swing.GroupLayout jPanelNumKeyBoardLayout = new javax.swing.GroupLayout(jPanelNumKeyBoard);
        jPanelNumKeyBoard.setLayout(jPanelNumKeyBoardLayout);
        jPanelNumKeyBoardLayout.setHorizontalGroup(
            jPanelNumKeyBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 203, Short.MAX_VALUE)
            .addGroup(jPanelNumKeyBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelNumKeyBoardLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelNumKeyBoard)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelNumKeyBoardLayout.setVerticalGroup(
            jPanelNumKeyBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 212, Short.MAX_VALUE)
            .addGroup(jPanelNumKeyBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelNumKeyBoardLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelNumKeyBoard)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanelKeyBoard.add(jPanelNumKeyBoard, "card43");

        jPanelSubmit.setPreferredSize(new java.awt.Dimension(53, 33));
        jPanelSubmit.setLayout(new java.awt.CardLayout());

        jPanelSubmitButton.setPreferredSize(new java.awt.Dimension(53, 33));

        jLabelSubmitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/sub_btn.png"))); // NOI18N

        javax.swing.GroupLayout jPanelSubmitButtonLayout = new javax.swing.GroupLayout(jPanelSubmitButton);
        jPanelSubmitButton.setLayout(jPanelSubmitButtonLayout);
        jPanelSubmitButtonLayout.setHorizontalGroup(
            jPanelSubmitButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 53, Short.MAX_VALUE)
            .addGroup(jPanelSubmitButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelSubmitButtonLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelSubmitButton)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelSubmitButtonLayout.setVerticalGroup(
            jPanelSubmitButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
            .addGroup(jPanelSubmitButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelSubmitButtonLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelSubmitButton)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanelSubmit.add(jPanelSubmitButton, "card2");

        jLabelSubmitHighlight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/sub_btn_high.png"))); // NOI18N

        javax.swing.GroupLayout jPanelSubmitHighlightLayout = new javax.swing.GroupLayout(jPanelSubmitHighlight);
        jPanelSubmitHighlight.setLayout(jPanelSubmitHighlightLayout);
        jPanelSubmitHighlightLayout.setHorizontalGroup(
            jPanelSubmitHighlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 53, Short.MAX_VALUE)
            .addGroup(jPanelSubmitHighlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelSubmitHighlightLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelSubmitHighlight)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelSubmitHighlightLayout.setVerticalGroup(
            jPanelSubmitHighlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
            .addGroup(jPanelSubmitHighlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelSubmitHighlightLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelSubmitHighlight)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanelSubmit.add(jPanelSubmitHighlight, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 203, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanelTextDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 53, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelKeyBoard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 150, Short.MAX_VALUE)
                    .addComponent(jPanelSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 245, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanelTextDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 212, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 33, Short.MAX_VALUE)
                    .addComponent(jPanelKeyBoard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanelSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 212, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel jLabelAlphaKeyBoard;
    public static javax.swing.JLabel jLabelKeyA;
    public static javax.swing.JLabel jLabelKeyB;
    public static javax.swing.JLabel jLabelKeyC;
    public static javax.swing.JLabel jLabelKeyD;
    public static javax.swing.JLabel jLabelKeyDel;
    public static javax.swing.JLabel jLabelKeyE;
    public static javax.swing.JLabel jLabelKeyEight;
    public static javax.swing.JLabel jLabelKeyF;
    public static javax.swing.JLabel jLabelKeyFive;
    public static javax.swing.JLabel jLabelKeyFour;
    public static javax.swing.JLabel jLabelKeyG;
    public static javax.swing.JLabel jLabelKeyH;
    public static javax.swing.JLabel jLabelKeyI;
    public static javax.swing.JLabel jLabelKeyJ;
    public static javax.swing.JLabel jLabelKeyK;
    public static javax.swing.JLabel jLabelKeyL;
    public static javax.swing.JLabel jLabelKeyM;
    public static javax.swing.JLabel jLabelKeyN;
    public static javax.swing.JLabel jLabelKeyNext;
    public static javax.swing.JLabel jLabelKeyNine;
    public static javax.swing.JLabel jLabelKeyO;
    public static javax.swing.JLabel jLabelKeyOne;
    public static javax.swing.JLabel jLabelKeyP;
    public static javax.swing.JLabel jLabelKeyPrev;
    public static javax.swing.JLabel jLabelKeyQ;
    public static javax.swing.JLabel jLabelKeyR;
    public static javax.swing.JLabel jLabelKeyS;
    public static javax.swing.JLabel jLabelKeySeven;
    public static javax.swing.JLabel jLabelKeySix;
    public static javax.swing.JLabel jLabelKeySpace;
    public static javax.swing.JLabel jLabelKeyT;
    public static javax.swing.JLabel jLabelKeyThree;
    public static javax.swing.JLabel jLabelKeyTwo;
    public static javax.swing.JLabel jLabelKeyU;
    public static javax.swing.JLabel jLabelKeyV;
    public static javax.swing.JLabel jLabelKeyW;
    public static javax.swing.JLabel jLabelKeyX;
    public static javax.swing.JLabel jLabelKeyY;
    public static javax.swing.JLabel jLabelKeyZ;
    public static javax.swing.JLabel jLabelKeyZero;
    public static javax.swing.JLabel jLabelNumKeyBoard;
    public static javax.swing.JLabel jLabelSubmitButton;
    public static javax.swing.JLabel jLabelSubmitHighlight;
    public static javax.swing.JLabel jLabelTextDisplay;
    public static javax.swing.JPanel jPanelAlphaKeyBoard;
    public static javax.swing.JPanel jPanelKeyA;
    public static javax.swing.JPanel jPanelKeyB;
    public static javax.swing.JPanel jPanelKeyBoard;
    public static javax.swing.JPanel jPanelKeyC;
    public static javax.swing.JPanel jPanelKeyD;
    public static javax.swing.JPanel jPanelKeyDel;
    public static javax.swing.JPanel jPanelKeyE;
    public static javax.swing.JPanel jPanelKeyEight;
    public static javax.swing.JPanel jPanelKeyF;
    public static javax.swing.JPanel jPanelKeyFive;
    public static javax.swing.JPanel jPanelKeyFour;
    public static javax.swing.JPanel jPanelKeyG;
    public static javax.swing.JPanel jPanelKeyH;
    public static javax.swing.JPanel jPanelKeyI;
    public static javax.swing.JPanel jPanelKeyJ;
    public static javax.swing.JPanel jPanelKeyK;
    public static javax.swing.JPanel jPanelKeyL;
    public static javax.swing.JPanel jPanelKeyM;
    public static javax.swing.JPanel jPanelKeyN;
    public static javax.swing.JPanel jPanelKeyNext;
    public static javax.swing.JPanel jPanelKeyNine;
    public static javax.swing.JPanel jPanelKeyO;
    public static javax.swing.JPanel jPanelKeyOne;
    public static javax.swing.JPanel jPanelKeyP;
    public static javax.swing.JPanel jPanelKeyPrev;
    public static javax.swing.JPanel jPanelKeyQ;
    public static javax.swing.JPanel jPanelKeyR;
    public static javax.swing.JPanel jPanelKeyS;
    public static javax.swing.JPanel jPanelKeySeven;
    public static javax.swing.JPanel jPanelKeySix;
    public static javax.swing.JPanel jPanelKeySpace;
    public static javax.swing.JPanel jPanelKeyT;
    public static javax.swing.JPanel jPanelKeyThree;
    public static javax.swing.JPanel jPanelKeyTwo;
    public static javax.swing.JPanel jPanelKeyU;
    public static javax.swing.JPanel jPanelKeyV;
    public static javax.swing.JPanel jPanelKeyW;
    public static javax.swing.JPanel jPanelKeyX;
    public static javax.swing.JPanel jPanelKeyY;
    public static javax.swing.JPanel jPanelKeyZ;
    public static javax.swing.JPanel jPanelKeyZero;
    public static javax.swing.JPanel jPanelNumKeyBoard;
    public static javax.swing.JPanel jPanelSubmit;
    public static javax.swing.JPanel jPanelSubmitButton;
    public static javax.swing.JPanel jPanelSubmitHighlight;
    public static javax.swing.JPanel jPanelTextDisplay;
    public static javax.swing.JTextField jTextFieldDestination;
    // End of variables declaration//GEN-END:variables
}
